### ISSUE TITLE
README Example

### ISSUE THREAD

**Issue by wallarelvo** [sybrenstuvel/Python-RVO2#1]
In the example in README.md, the time step needs to be 1.0 / 60 because 1 / 60 is interpreted as 0 and thus the simulation does not progress.

**Comment by sybrenstuvel** [comment]
That's only true for Python 2.x. IMO, when you're using an older version of Python, you need to watch out for incompatibilities. However, since it's only a small change, I'll change it in the README file.

**Comment by wallarelvo** [comment]
Okay, I just noticed that in your shebang on the top of the example, you were calling `python` which is usually associated with python 2.7.x. To indicate to your system (unless you are using Arch) that you would like to use python 3, you usually need to have `python3` instead.

Thanks though.

**Comment by sybrenstuvel** [comment]
I understand that not that many systems have Python 3 as default. However, I mostly work with virtualenvs, and then it's fine to have it like that. And I feel that we (as in: the world) should not linger on Python 2 any more ;-)

**Comment by wallarelvo** [comment]
I see, you are a Python 3 supporter. What is so good about it anyway? I
heard they were going to take the functional programming aspects of Python
out of it.

--Alex

**Comment by sybrenstuvel** [comment]
Well, with Stüvel as last name, you don't know how happy I am with a proper separation of bytes and strings. Besides that, I don't see any convincing reason to stick to an old, hardly developed version.

**Comment by sybrenstuvel** [comment]
PS: I do want to support Python 2.7 with this library, as I like people using it for as many applications as possible ;-)

**Comment by sybrenstuvel** [comment]
PPS: they're not going to remove functional programming aspects. Maybe they remove some functions like 'map' and 'filter', because they can both be replaced by list comprehensions (which are more expressive).

**Comment by wallarelvo** [comment]
I looked through some stuff for Python 3.5 and I am quite pleased by the
function annotations. I think this will make me move to it.

--Alex
