### ISSUE TITLE
Implementation of NH-ORCA

### ISSUE THREAD

**Issue by Yahnit** [sybrenstuvel/Python-RVO2#12]
Do you have the implementation of ORCA for non-holonomic robots? 
Or do you know  anyone who has worked on this?
Your help will be appreciated!

Thanks in Advance

**Comment by SamNew1** [comment]
have you found the github code for ORCA of non-holonomic robots?

**Comment by sybrenstuvel** [comment]
This repository is not affiliated with the authors of the ORCA algorithm. It's just for the Python wrapper of their library.

**Comment by JiayunjieJYJ** [comment]
> Do you have the implementation of ORCA for non-holonomic robots? Or do you know anyone who has worked on this? Your help will be appreciated!
> 
> Thanks in Advance

Hi, I have the same question, have you found it?

**Comment by JiayunjieJYJ** [comment]
> have you found the github code for ORCA of non-holonomic robots?

Hi, I have the same question, have you found it?
