### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by SungBeom-Choi** [sybrenstuvel/Python-RVO2#15]
running build
running build_ext
Error: could not load cache
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 20, in run
    subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir)
  File "C:\Users\chois\AppData\Local\Continuum\anaconda3\envs\crowdnav\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.

Why this error is happen?

**Comment by SUNGBEOMCHOI** [comment]
Solved it :) 
Just delete empty build directory.

**Comment by huikunbi** [comment]
Hi, have you configured python-rvo2 under windows successfully? I have some problems, have you met before? Thank you.
When I run “python setup.py build”, I have errors like this:


running build
running build_ext
Microsoft (R) build engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. all rights reserved.

  RVO.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\src\Debug\RVO.lib
  Blocks.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\examples\Debug\Blocks.exe
  Circle.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\examples\Debug\Circle.exe
  Roadmap.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\examples\Debug\Roadmap.exe
building'rvo2' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc/ -ID:\software\Anaconda3\envs\python32-rl\include -ID:\software\Anaconda3\envs\python32-rl\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\ Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC :\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\ Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16 .27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0 \shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt ""-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpsrc/rvo2.cpp /Fobuild\temp.win32-3.6\Release\src/rvo2.obj- fPIC
cl: Command line warning D9002: Ignore unknown option "-fPIC"
rvo2.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED ,ID=2 /MANIFESTUAC:NO /LIBPATH:build/RVO2/src /LIBPATH:D:\software\Anaconda3\envs\python32-rl\libs /LIBPATH:D:\software\Anaconda3\envs\python32-rl\PCbuild \win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86 )\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\ x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community \VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\ x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86" "/LIBPAT H:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" RVO.lib /EXPORT:PyInit_rvo2 build\temp.win32-3.6\Release\src/rvo2.obj /OUT :build\lib.win32-3.6\rvo2.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\src\rvo2.cp36-win32.lib
RVO.lib(RVOSimulator.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj)
RVO.lib(RVOSimulator.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj)
RVO.lib(Agent.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj)
RVO.lib(Agent.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj)
RVO.lib(KdTree.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj)
RVO.lib(KdTree.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj)
RVO.lib(Obstacle.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj)
RVO.lib(Obstacle.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj)
  Creating library build\temp.win32-3.6\Release\src\rvo2.cp36-win32.lib and object build\temp.win32-3.6\Release\src\rvo2.cp36-win32.exp
LINK: warning LNK4098: The default library "MSVCRTD" conflicts with other libraries; please use /NODEFAULTLIB:library
RVO.lib(RVOSimulator.obj): error LNK2001: Unresolved external symbol __imp___invalid_parameter
RVO.lib(Agent.obj): error LNK2001: Unresolved external symbol __imp___invalid_parameter
RVO.lib(KdTree.obj): error LNK2001: Unresolved external symbol __imp___invalid_parameter
RVO.lib(RVOSimulator.obj): error LNK2001: Unresolved external symbol __imp___CrtDbgReport
RVO.lib(Agent.obj): error LNK2001: Unresolved external symbol __imp___CrtDbgReport
RVO.lib(KdTree.obj): error LNK2001: Unresolved external symbol __imp___CrtDbgReport
build\lib.win32-3.6\rvo2.cp36-win32.pyd: fatal error LNK1120: 2 unresolved external commands
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120

**Comment by adamsigal** [comment]
> Solved it :) Just delete empty build directory.

You're a lifesaver, this worked for me!

**Comment by IOwenI** [comment]
> 

Have you solved it? Please share with me if you finished, thank you so much!

**Comment by IOwenI** [comment]
> Hi, have you configured python-rvo2 under windows successfully? I have some problems, have you met before? Thank you. When I run “python setup.py build”, I have errors like this:
> 
> running build running build_ext Microsoft (R) build engine version 15.9.21+g9802d43bc3 for .NET Framework Copyright (C) Microsoft Corporation. all rights reserved.
> 
> RVO.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\src\Debug\RVO.lib Blocks.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\examples\Debug\Blocks.exe Circle.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\examples\Debug\Circle.exe Roadmap.vcxproj -> D:\BHK\MyProject\RL\Python-RVO2\build\RVO2\examples\Debug\Roadmap.exe building'rvo2' extension C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc/ -ID:\software\Anaconda3\envs\python32-rl\include -ID:\software\Anaconda3\envs\python32-rl\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\ Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC :\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\ Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16 .27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0 \shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt ""-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpsrc/rvo2.cpp /Fobuild\temp.win32-3.6\Release\src/rvo2.obj- fPIC cl: Command line warning D9002: Ignore unknown option "-fPIC" rvo2.cpp C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED ,ID=2 /MANIFESTUAC:NO /LIBPATH:build/RVO2/src /LIBPATH:D:\software\Anaconda3\envs\python32-rl\libs /LIBPATH:D:\software\Anaconda3\envs\python32-rl\PCbuild \win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86 )\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\ x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community \VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\ x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86" "/LIBPAT H:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" RVO.lib /EXPORT:PyInit_rvo2 build\temp.win32-3.6\Release\src/rvo2.obj /OUT :build\lib.win32-3.6\rvo2.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\src\rvo2.cp36-win32.lib RVO.lib(RVOSimulator.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj) RVO.lib(RVOSimulator.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj) RVO.lib(Agent.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj) RVO.lib(Agent.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj) RVO.lib(KdTree.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj) RVO.lib(KdTree.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj) RVO.lib(Obstacle.obj): error LNK2038: mismatch detected for "_ITERATOR_DEBUG_LEVEL": The value "2" does not match the value "0" (in rvo2.obj) RVO.lib(Obstacle.obj): error LNK2038: mismatch detected for "RuntimeLibrary": The value "MDd_DynamicDebug" does not match the value "MD_DynamicRelease" (in rvo2.obj) Creating library build\temp.win32-3.6\Release\src\rvo2.cp36-win32.lib and object build\temp.win32-3.6\Release\src\rvo2.cp36-win32.exp LINK: warning LNK4098: The default library "MSVCRTD" conflicts with other libraries; please use /NODEFAULTLIB:library RVO.lib(RVOSimulator.obj): error LNK2001: Unresolved external symbol __imp___invalid_parameter RVO.lib(Agent.obj): error LNK2001: Unresolved external symbol __imp___invalid_parameter RVO.lib(KdTree.obj): error LNK2001: Unresolved external symbol __imp___invalid_parameter RVO.lib(RVOSimulator.obj): error LNK2001: Unresolved external symbol __imp___CrtDbgReport RVO.lib(Agent.obj): error LNK2001: Unresolved external symbol __imp___CrtDbgReport RVO.lib(KdTree.obj): error LNK2001: Unresolved external symbol __imp___CrtDbgReport build\lib.win32-3.6\rvo2.cp36-win32.pyd: fatal error LNK1120: 2 unresolved external commands error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe' failed with exit status 1120

Have you solved it? Please share with me if you finished, thank you so much!
