### ISSUE TITLE
Missing RVOSimulator destructor causes memory leak in rvo.pyx

### ISSUE THREAD

**Issue by Shuijing725** [sybrenstuvel/Python-RVO2#17]
Hello Sybren,

Thank you for making the RVO2 code available in python! 

However, I found a small bug and would appreciate if you could fix it:
In rvo.pyx, the destructor of RVOSimulator class is missing. This causes memory leak because an RVOSimulator object contains other objects, such as Agents, Obstacles, kdTree, etc. For this reason, the destructor of RVOSimulator is overwritten in the original C++ code and we must export the destructor to Python in rvo.pyx. 

Please add the following line under `cdef class PyRVOSimulator` in line 79:
`    def __dealloc__(self):
        del self.thisptr`

**Comment by danieldugas** [comment]
I can confirm this leak when running the latest master commit (9955301)

![memory-profile](https://user-images.githubusercontent.com/1926730/89661508-13cb2180-d8d3-11ea-95e3-e3c43b877efa.png)

**Comment by sybrenstuvel** [comment]
This should be fixed now, thanks @danieldugas !
