### ISSUE TITLE
ERROR: No matching distribution found for Cython==0.21.1

### ISSUE THREAD

**Issue by Geonhee-LEE** [sybrenstuvel/Python-RVO2#26]
Hi, thanks for your contribution.

When I tried to install `pip install ~`, some error occurs like following:
```
ERROR: No matching distribution found for Cython==0.21.1
```
![image](https://user-images.githubusercontent.com/12562147/147408919-8016e9d9-8766-4d3a-8c56-9502ddf95076.png)

**Comment by chennnuo** [comment]
Hello, you can directly change Cython==0.21.1 in requirements.txt to Cython and try again.

**Comment by chennnuo** [comment]
Or modify your python version to 3.6.I recommend this way.
