### ISSUE TITLE
RVO2-3D

### ISSUE THREAD

**Issue by johnroper100** [sybrenstuvel/Python-RVO2#3]
Hi, I was wondering, can this be used for RVO2-3D as well? How can I set it up so that it does?

**Comment by sybrenstuvel** [comment]
Hey John. Since RVO2-3D is a completely different library, these bindings won't work. However, you could of course look at the [rvo2.pyx](https://github.com/sybrenstuvel/Python-RVO2/blob/master/src/rvo2.pyx) file as an example, and use it to create your own bindings for the RVO2-3D library.

**Comment by johnroper100** [comment]
Thanks!
