### ISSUE TITLE
Simulate as a non-holonomic robot.

### ISSUE THREAD

**Issue by yuqikong** [sybrenstuvel/Python-RVO2#34]
My robot is a non-holonomic robot, which can only move forward and rotate, but cannot move sideways. But I looked at the example.py file and found that the robot of the simulation simulator is a holonomic robot. How can I modify it into a holonomic robot?

**Comment by sybrenstuvel** [comment]
Hi @yuqikong . This repository is only for the Python bindings. For questions about the RVO library itself, please go to https://github.com/snape/RVO2

**Comment by JiayunjieJYJ** [comment]
> My robot is a non-holonomic robot, which can only move forward and rotate, but cannot move sideways. But I looked at the example.py file and found that the robot of the simulation simulator is a holonomic robot. How can I modify it into a holonomic robot?

Hi, I have the same question, can we have a discussion?
