### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by mimooh** [sybrenstuvel/Python-RVO2#5]
Installation fails:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

git clone https://github.com/sybrenstuvel/Python-RVO2.git
Cloning into 'Python-RVO2'...
remote: Counting objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0), pack-reused 156
Receiving objects: 100% (156/156), 93.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (84/84), done.
Checking connectivity... done.

cd Python-RVO2/

pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Cython==0.21.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
g201:Python-RVO2$ python setup.py build
Compiling src/rvo2.pyx because it changed.
[1/1] Cythonizing src/rvo2.pyx
running build
running build_ext
error: [Errno 20] Not a directory

**Comment by mimooh** [comment]
Sorry, I was missing cmake

**Comment by sybrenstuvel** [comment]
Thanks for letting us know; now people can google the error message and find the solution (installing cmake) ;-)
