### ISSUE TITLE
Install error for Ubuntu16.04

### ISSUE THREAD

**Issue by Aaricis** [sybrenstuvel/Python-RVO2#9]
I run "python setup.py install", but it can not work.
![2018-04-24 21-33-19](https://user-images.githubusercontent.com/35218694/39190250-c4ae3c54-4806-11e8-879d-4d9c77bded0a.png)

**Comment by sybrenstuvel** [comment]
Please read what's written in the error message and the linked documentation.

**Comment by Catosis** [comment]
sudo python setup.py install

**Comment by sybrenstuvel** [comment]
Throwing sudo at a permission problem is generally a bad idea. Maybe for this user a virtualenv is better, or maybe passing `setup.py` a writable install directory, or building in-place. It's hard to tell without any context which is the most suitable approach.

**Comment by Aaricis** [comment]
Thanks a lot. It works.
